In [10]:
# all imports
from helpers import *
from quick_find import QuickFind
from quick_union import QuickUnion

In [11]:
graph_size=20                  # number of nodes [Graph size]
union_size=10                #number of desired union operations

In [12]:
unions=create_network(graph_size,union_size)

In [13]:
qf=QuickFind(graph_size)
for un in unions:
    if un[0] is not un[1]:
        result=qf.union(un[0], un[1])

In [14]:
print(unions)

[[4, 15], [4, 0], [10, 7], [10, 6], [16, 13], [3, 19], [13, 10], [3, 10], [7, 1], [16, 18]]


In [15]:
import numpy as np
print(np.array(range(0,graph_size)))
print(qf.nodes)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0 18  2 18  0  5 18 18  8  9 18 11 12 18 14  0 18 17 18 18]


In [16]:
qu=QuickUnion(graph_size)
for un in unions:
    if un[0] is not un[1]:
        result=qu.union(un[0], un[1])

In [17]:
print(np.array(range(0,graph_size)))
print(qu.nodes)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0 18  2 19 15  5  1  6  8  9  7 11 12  6 14  0 13 17 18  6]


In [18]:
cu=union_check(graph_size, union_size)
for un in cu:
    print(un[0], un[1],
         qf.find(un[0], un[1]),
         qu.find(un[0], un[1]))
    

9 12 False False
10 18 True True
0 0 True True
6 11 False False
18 19 True True
18 8 False False
10 9 False False
18 9 False False
13 3 True True
8 19 False False
